export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const CHANGE_USER = 'CHANGE_USER'

export const REGISTER = 'REGISTER'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const FETCH_BANNER_HOMEPAGE = 'FETCH_BANNER_HOMEPAGE'
export const FETCH_BANNER_HOMEPAGE_SUCCESS = 'FETCH_BANNER_HOMEPAGE_SUCCESS'
export const FETCH_BANNER_HOMEPAGE_FAILED = 'FETCH_BANNER_HOMEPAGE_FAILED'

export const CLICK_HOME_BANNER_CATEGORY = 'CLICK_HOME_BANNER_CATEGORY'
export const CLICK_HOME_BANNER_CATEGORY_SUCCESS = 'CLICK_HOME_BANNER_CATEGORY_SUCCESS'
export const CLICK_HOME_BANNER_CATEGORY_FAILED = 'CLICK_HOME_BANNER_CATEGORY_FAILED'

export const CLICK_HOME_FOOD_SUGGESTION = 'CLICK_HOME_FOOD_SUGGESTION' 
export const CLICK_HOME_FOOD_PICK_CATEGORY = 'CLICK_HOME_FOOD_PICK_CATEGORY'   
