export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const CHANGE_USER = 'CHANGE_USER'

export const REGISTER = 'REGISTER'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED'
 
export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_FAILED = 'GET_CATEGORIES_FAILED'

export const CLICK_HOME_BANNER_CATEGORY = 'CLICK_HOME_BANNER_CATEGORY'
export const CLICK_HOME_BANNER_CATEGORY_SUCCESS = 'CLICK_HOME_BANNER_CATEGORY_SUCCESS'
export const CLICK_HOME_BANNER_CATEGORY_FAILED = 'CLICK_HOME_BANNER_CATEGORY_FAILED'

export const CLICK_HOME_FOOD_SUGGESTION = 'CLICK_HOME_FOOD_SUGGESTION' 
export const CLICK_HOME_FOOD_PICK_CATEGORY = 'CLICK_HOME_FOOD_PICK_CATEGORY'   
